#!/bin/sh
#
# Set up environment variables for general build tool to operate
#

if ! [ -f ./buildenv ]; then
	echo "Need to source from the buildenv directory" >&2
	return 0
fi

export ZOPEN_ROOT="${PWD}"
export ZOPEN_TYPE="GIT"

export ZOPEN_GIT_URL="https://github.com/madler/zlib.git"
export ZOPEN_GIT_DEPS="git make"
export ZOPEN_CONFIGURE_MINIMAL=Y     
export ZOPEN_EXTRA_CFLAGS="-std=c11"
export ZOPEN_MAKE_OPTS='libz.a'
export ZOPEN_CHECK='skip'
